export const products = [
  {
    id: 1,
    images: ["product1.png"],
    category: "Kids",
    title: "Yellow T-Shirt",
    price: {
      main: 180,
      off: 300,
    },
    tag: "40%",
    rate: 4,
    max:8,
		sale: 2324,
		qty:0,
		total:0
  },
  {
    id: 2,
    images: ["product2.png"],
    category: "Women",
    title: "Ethnic Kurti",
    price: {
      main: 220,
      off: 250,
    },
    tag: "",
    rate: 3,
    max:6,
		sale: 3237,
  },
  {
    id: 3,
    images: ["product3.png"],
    category: "Women",
    title: "Kurtis, Tunics & Tops",
    price: {
      main: 280,
      off: 350,
    },
    tag: "New",
    rate: 5,
    max:5,
		sale: 102,
  },
  {
    id: 4,
    images: ["product4.png"],
    category: "Men",
    title: "Round Neck T-shirt",
    price: {
      main: 120,
      off: 150,
    },
    tag: "",
    rate: 1,
    max:4,
		sale: 1235,
  },
  {
    id: 5,
    images: ["product5.png"],
    category: "Kids",
    title: "Kurti Full Sleev",
    price: {
      main: 200,
      off: 300,
    },
    tag: "",
    rate: 4.5,
    max:2,
		sale: 502,
  },
  {
    id: 6,
    images: ["product6.png"],
    category: "Women",
    title: "Silk Saree - Printied",
    price: {
      main: 320,
      off: 410,
    },
    tag: "",
    rate: 2,
    max:8,
		sale: 3400,
  },
  {
    id: 7,
    images: ["product7.png"],
    category: "Men",
    title: "Multi Purpose Jacket",
    price: {
      main: 510,
      off: 705,
    },
    tag: "",
    rate: 2,
    max:3,
		sale: 2454,
  },
  {
    id: 8,
    images: ["product8.png"],
    category: "Men",
    title: "Jacket",
    price: {
      main: 400,
      off: 480,
    },
    tag: "",
    rate: 2,
    max:7,
		sale: 1340,
  },
]
